apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: secret-mysql
  namespace: database
spec:
  encryptedData:
    password: AgCHut6k8lYTW2uGeQWvTgIKY2UnsjYeyCrlYiBqkWPff1hP9Tl0rVlDsVSzu1TRevzWjnXu05zSMJS3/rJ7wZOfX3jrYY+B6RTnQL/eZ7fZGv3smEChdQv7oeTHckkndV0RhHS6wk9k2PJRit7GU2UDydcVdE/PukVxi0jrsWeueRUC+aAlwrowQ35Gr340fxl3VaZBX9g96Nk4OyQKOgTAWc0J/xMKX8T++MqTDlhFVzizq4TQslyPvguGhm7mYfeLccoG4CDKBa9Ogk0KgdV8gfTCOinMPjZmdG0l6iNhuH5Edmkd2SuGDSZJvXMuTsKnypYVt2jj5SITtKukR2AKEHBoWik+WvmS8t82e03l6VFcClDACWrJ1oQduzlgWUxHmghK8HXgeYOOLkh2qhn5urUGMmxV6Iyn0TdGgYU4LVI5cgNhjGouSr+6laJgzsmQusTKIeaFYvosM6pSOjKJ/On4IKzvD71knXlSrYdCN6a7WBysnfnRz6GuoNOhP9ILR6LE6M5A3x5wCxvFv2KtlcnDpL9SPdNjzifvoF2V3yx6BE33abRZzNcquALYAmVb87OuCxGL1RDQ3LNcFJubkmXvtii0YKk/9pFeQcgWKVm3QfwZz3LGI3HNZYOv9BYuUBZyZfTXIaWeEtD55b5a3Gmcb7g3F3Ak/HBMzTkfVkw6dHhemmqkIYAEvpkfhcXcVB9ZhtxYTshg5qsOj08VYSfdT3sFvlz0
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: secret-mysql
      namespace: database

