apiVersion: v1
kind: Secret
metadata:
    name: secret-mysql
    namespace: database
stringData:
    password: ENC[AES256_GCM,data:S8+BU7yqzrd+t37sk0q4AbXHMYFtlazK4Q==,iv:4jyUdNtE085n5vO7gydrtwqKLWa/YSlPVRoryFq1HKU=,tag:/lnWhF2OkKUCSGarNqpLlA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-07-17T12:59:31Z"
    mac: ENC[AES256_GCM,data:XaXqUjUW4dZPxYBNt8yYz/ZIjKBZbUnNnxfY9INSUoZgGF4NeSDo56nR63KPHL+se8XUvI02DPP5Pl2hjZzoNsJiU1BSGk5KCOOK9t4i5ypCvri0ubSgVAPhUQEkxa0xRU5iblrX25L3lQGTvA+quHA5l83/xgpGD4QQRFEIF80=,iv:7SfIyNHjqH5kJmRI/4Hdt0McM4ZkPabzGhCaAnt51aQ=,tag:+ypA9HhZMUf7Uwduh1Q23w==,type:str]
    pgp:
        - created_at: "2025-07-17T12:59:31Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA0GlH+dr3YPSAQwAlGUNWaW4RrXQKi22YwYLPtRYbsvKDDqgEUsBY+5HCKMw
            c3UWNDoOIKNMkHYtEYnilzDrtx3tEi1FjsO86rCiP6/+iI0w8tJMyV3OxhAgzn2M
            fGtrUzJ7M2fYFyy3t9rudpTM6Ju5TTwnHVPAQSUiAIR30k7f3e91exn+ZwJYvWLh
            6Gj+Q6ips9Qv20fymnYWPiHIUbbmwx5jKVRiAz2/kjodTEa37398cB7poJABuTAV
            xyM+i9jBCzb5hWak9WCHGBI+DYLS5Gkv3omk9VTQHhK7lAwJi+pqYBwXa4PAqTS2
            Uv2oYwEqSzam8hNuKgzjMlwdEq5HZ48Kab0BBit0cDp1W9g4TRMiQOY9kd4awtbp
            c/EX4EwbENzPjplcUNIRDRBS1L4dTa6EbYY4VIWz5wUJJsOBv/STKcV/c2tSA6jN
            Q1oTrBk46YbYoe37Se0CIU5SLE585l+Xun92e+xu6CvhYsQaSaH1F3ZGcVfoy63R
            LQNUIZ7JKSWhY/gMk9Xy1GgBCQIQQFaDyaDzOYcWPN1HrIeaJ9mZCaHinL8IZxc6
            20GmTKyS1aT2nfz7S5qCD+GXwU7wrEyxNLWDDi2d2naMTxry47+Hx9VqsElHyr8m
            slArLJip9nFIxfXeb9w64r7sJX+wPd5apQ==
            =NLmJ
            -----END PGP MESSAGE-----
          fp: 47531F33DD244A70103B7574F9EDB41DF5AB80C4
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
